### ISSUE TITLE
vscode-nim : how to get it to work on Win10 ?

### ISSUE THREAD

**Issue by dreamflow** [nim-lang/vscode-nim#93]
when i open a .nim file in vscode ,
the vscode-nim extension is not launched
= vscode output is empty
and no nimlangserver.exe process ist started .

how to get it to work ?

my environement is :

`Win10 pro 64bit 22H2`

vscode 64bit : `1.92.2`

vscode-nim extension : `nim-lang.org v1.0.2`

nimlangserver 64bit :
nimlangserver.exe -v : `1.5.0`
downloaded from "Latest Nimlangserver Binaries" from
https://github.com/nim-lang/langserver/releases/tag/latest

```
nim -v
Nim Compiler Version 2.1.9 [Windows: amd64]
Compiled at 2024-08-20
```

vscode -> settings.json :
```json
"nim.lsp.path": "C:/nimlangserver.exe",
"nim.lintOnSave": false,
```

nim.exe and nimlangserver.exe
are both reachable via the `Path` env-var
within the vscode terminal .

**Comment by treeform** [comment]
I have same issue. It jus says:

![image](https://github.com/user-attachments/assets/8f124d8d-a055-4f7e-b484-4ca473278c60)

While it works on command line:

![image](https://github.com/user-attachments/assets/2f998e3d-f28b-4863-94cc-01b217ff71b0)

**Comment by jmgomez** [comment]
@dreamflow the last released version of `nimlangserver` is `0.14.0` can you try with that one? `latest`

@treeform what does the `Nim Language Server` output windows says?

**Comment by treeform** [comment]
This is what I have in that window: ```
DBG Router: dispatching                        method=initialize id=0
DBG Initialize received...                    
DBG Registering monitor for process            pid=19032
DBG Initialize completed. Trying to start nimsuggest instances
DBG Router: sending response                   method=initialize id=0
DBG Router: dispatching                        method=initialized id=null
DBG Client initialized.                       
DBG Requesting configuration from the client  
DBG Got response for the didChangeConfiguration registration: res=null
DBG Received the following configuration       configuration="[{\"project\":[],\"projectMapping\":[],\"test-project\":\"\",\"buildOnSave\":false,\"buildCommand\":\"c\",\"runOutputDirectory\":\"\",\"lintOnSave\":true,\"enableNimsuggest\":false,\"provider\":\"lsp\",\"useNimsuggestCheck\":false,\"logNimsuggest\":false,\"licenseString\":\"\",\"nimsuggestRestartTimeout\":60,\"nimprettyIndent\":0,\"nimprettyMaxLineLen\":80,\"lsp\":{\"path\":\"C:/Users/me/.nimble/pkgs2/nimlangserver-1.4.0-20579f6b83a2b3b7b2af7e3e9cef94c27266fe1b/nimlangserver.exe\"},\"inlayHints\":{\"typeHints\":{\"enable\":true},\"parameterHints\":{\"enable\":true},\"exceptionHints\":{\"enable\":true,\"hintStringLeft\":\"🔔\",\"hintStringRight\":\"\"}},\"debug\":{\"type\":\"lldb\"},\"notificationVerbosity\":\"info\",\"notificationTimeout\":15}]"```

**Comment by jmgomez** [comment]
Just that? Sounds like it's hanging for some reason. What version of the `nimlangserver` are you using? Also, does it happen to you for all nim files you try to load? (once it hangs, it wont pick another file I bet, so make sure it starts again in order to test this) 
Thanks!

**Comment by dreamflow** [comment]
> last released version of nimlangserver is 0.14.0 can you try with that one?

@jmgomez :
sure , now i've tried it with the current release version 1.4.0
of the nimlangserver.exe (nimlangserver-1.4.0-windows-amd64.zip)
with the newest nim.exe version 2.1.99 [Windows: amd64] 2024-08-31 .
and i've also tried it with and without the line
`"nim.lsp.path": "C:/nimlangserver.exe",`
in the vscode "settings.json" .
but the outcome is the same :
when i open a .nim file in vscode ,
the vscode-nim extension is not launched
= vscode output is empty
and no nimlangserver.exe process is started .

**Comment by jmgomez** [comment]
This is odd. I need to setup a Win 10 VM to repro it. Win 11 seems to work just fine, will try to get back to to you during next week.

**Comment by jmgomez** [comment]
I just tried with `nimlangserver` `0.14.0` and I could reproduce it, however, building from sources did work. Do you mind to try to use the sources version and report back?

As a side note, this will be merge soon: https://github.com/nim-lang/langserver/pull/225 and once properly tested it will be released. There have been a lot of issues fixed as part of the refactor.

**Comment by dreamflow** [comment]
> try to use the sources version and report back

i've now compiled nimlangserver.exe from source
and running `nimlangserver.exe -v` returns `1.4.0` .

but this fresh compiled nimlangserver.exe also
doesn't work in vscode :
the vscode-nim extension is not launched
= vscode "nim"-output is empty
and no nimlangserver.exe process is started .

earlier versions of the nimlangserver.exe
did work fine in vscode .

**Comment by jmgomez** [comment]
What's the output log is there something?

**Comment by dreamflow** [comment]
> What's the output log is there something?
in the vscode terminal panel ,
the "nim"-output windows is empty ,
but had log content with older
nimlangserver.exe versions .

**Comment by jmgomez** [comment]
The output should be "Nim Language Server". Get rid of the previous one to make sure it is picking the right version

**Comment by dreamflow** [comment]
> Get rid of the previous one to make sure it is picking the right version

yes , i make sure to have only one nimlangserver.exe
available via the %path% env var .

 > The output window should be "Nim Language Server".

i've checked : when opening a nim file , then there is
available an "output"-window named "Nim" , but never
an "output"-window named "Nim Language Server" .

 > What's the output log is there something?

in vscode i've disabled all extensions , except the
"nim-lang.org"-extension . for the ''output"-log-window
i choose ''Extension Host'' and activate "trace"-mode .
now when i drag-&-drop a nim file into vscode ,
in the ''output'-log'-window appears :

```js
2024-09-04 10:48:42.745 [info] ExtensionService#_doActivateExtension NimLang.nimlang, startup: false, activationEvent: 'onLanguage:nim'
2024-09-04 10:48:42.746 [trace] ExtensionService#loadCommonJSModule file:///c:/programs/vscode/64bit/data/extensions/nimlang.nimlang-1.0.2/out/nimvscode.js
2024-09-04 10:48:42.746 [trace] ExtensionService#loadExtensionContext NimLang.nimlang
2024-09-04 10:48:42.931 [trace] ExtensionService#_callActivateOptional NimLang.nimlang
2024-09-04 10:48:42.931 [trace] ExtHostCommands#registerCommand nim.run.file
2024-09-04 10:48:42.932 [trace] ExtHostCommands#registerCommand nim.debug.file
2024-09-04 10:48:42.932 [trace] ExtHostCommands#registerCommand nim.check
2024-09-04 10:48:42.932 [trace] ExtHostCommands#registerCommand nim.restartNimsuggest
2024-09-04 10:48:42.932 [trace] ExtHostCommands#registerCommand nim.execSelectionInTerminal
2024-09-04 10:48:42.932 [trace] ExtHostCommands#registerCommand nim.clearCaches
2024-09-04 10:48:42.933 [trace] ExtHostCommands#registerCommand nim.listCandidateProjects
2024-09-04 10:48:42.933 [trace] ExtHostCommands#registerCommand nim.showNimLangServerStatus
2024-09-04 10:48:42.933 [trace] ExtHostCommands#registerCommand nim.showNotification
2024-09-04 10:48:42.933 [trace] ExtHostCommands#registerCommand nim.onDeleteNotification
2024-09-04 10:48:42.933 [trace] ExtHostCommands#registerCommand nim.onClearAllNotifications
2024-09-04 10:48:42.937 [error] Activating extension NimLang.nimlang failed due to an error:
2024-09-04 10:48:42.937 [error] TypeError: Cannot read properties of undefined (reading 'uri')
	at setNimDir_553649168 (c:\programs\vscode\64bit\data\extensions\nimlang.nimlang-1.0.2\out\nimvscode.js:14978:76)
	at activate_553649241 (c:\programs\vscode\64bit\data\extensions\nimlang.nimlang-1.0.2\out\nimvscode.js:19705:5)
	at z.kb (c:\programs\vscode\64bit\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:160:13608)
	at z.jb (c:\programs\vscode\64bit\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:160:13280)
	at c:\programs\vscode\64bit\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:160:11267
	at async m.n (c:\programs\vscode\64bit\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:6409)
	at async m (c:\programs\vscode\64bit\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:6372)
	at async m.l (c:\programs\vscode\64bit\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:5829)
2024-09-04 10:48:43.248 [trace] [vscode.merge-conflict] INVOKE provider 'x=>x.provideCodeLenses(u.URI.revive(G),J)'
2024-09-04 10:48:43.249 [trace] ExtHostCommands#executeCommand setContext
2024-09-04 10:48:43.250 [trace] ExtHostCommands#executeCommand _setContext
2024-09-04 10:48:43.251 [trace] [vscode.merge-conflict] provider DONE after 4ms
```

**Comment by jmgomez** [comment]
hmm, that's something else then. Can you try out with the custom build attached? You need to unzip it and then execute "Install from vsix" from the vscode command palette 

[nimvscode-1.0.3.vsix.zip](https://github.com/user-attachments/files/16868066/nimvscode-1.0.3.vsix.zip)

**Comment by dreamflow** [comment]
> Can you try out with the custom build attached

i've installed it and now the "output"-log-window
named "Nim Lsp" appears , that stays empty when
opening a nim file . the "output"-log-window 
'Extension Host'' shows :

```ruby
2024-09-04 12:04:50.634 [trace] [vscode.merge-conflict] INVOKE provider 'x=>x.provideCodeLenses(u.URI.revive(G),J)'
2024-09-04 12:04:50.642 [trace] ExtHostCommands#executeCommand setContext
2024-09-04 12:04:50.643 [trace] ExtHostCommands#executeCommand _setContext
2024-09-04 12:04:50.643 [trace] [vscode.merge-conflict] provider DONE after 8ms
```

**Comment by jmgomez** [comment]
The log looks fine afaict
This is a clean install of Win10, with latest sources of `nimlangserver` and the extension build I sent over. Not sure if something else is going on in your system
<img width="1817" alt="image" src="https://github.com/user-attachments/assets/89557f72-21dc-482f-8110-8d58ef65960d">

**Comment by dreamflow** [comment]
many thanks for your patient support !

 > Not sure if something else is going on in your system

i'm running vscode in portable mode
https://code.visualstudio.com/docs/editor/portable

i'm using the latest nim nightly build for branch devel
nim-2.1.99-windows_x64.zip , extract it , but dont't run
finish.exe , just add the absolute path of nim's "bin/" dir
to the %path% env var and then check `nim -v` .

iv'e tried it also on an other Win10 pc
and got the same results .

**Comment by jmgomez** [comment]
Did you mind to test it with a non portable version? If that ends up being the issue, I will fix it 

Thanks

**Comment by dreamflow** [comment]
i've installed the (non portable)
vscode standard installation version
VSCodeUserSetup-x64-1.92.2.exe
and nimvscode-1.0.3.vsix.zip and
made available in the %Path% env var
nim's "bin/" dir and the dir that
contains the fresh compiled
nimlangserver.exe and checked
successfully `nim -v` and
`nimlangserver -v` .

when opening this nim file
```nim
var test = 1
test += 1
```
the "output"-log-window "Nim Lsp" shows :
```ruby
DBG Router: dispatching                        method=initialize id=0
DBG Initialize received...                    
DBG Registering monitor for process            pid=2480
DBG Initialize completed. Trying to start nimsuggest instances
DBG Router: sending response                   method=initialize id=0
DBG Router: dispatching                        method=initialized id=null
DBG Client initialized.                       
DBG Requesting configuration from the client  
DBG Router: dispatching                        method=textDocument/didOpen id=null
DBG New document opened for URI:               uri=file:///e%3A/test.nim
DBG Router: dispatching                        method=textDocument/documentSymbol id=1
DBG Router: dispatching                        method=textDocument/codeAction id=2
DBG Got response for the didChangeConfiguration registration: res=null
DBG Shutting down due to an error:             msg="input(1, 0) Error: { expected"
DBG Stack trace:                               stack_trace="parsejson.nim(518)       raiseParseErr\n???                      start (Async)\nasyncfutures.nim(381)    read\n"
Shutting down due to an error: input(1, 0) Error: { expected
parsejson.nim(518)       raiseParseErr
???                      start (Async)
asyncfutures.nim(381)    read

[Info  - 6:21:16 PM] Connection to server got closed. Server will restart.
true
[Error - 6:21:16 PM] Server process exited with code 1.
DBG Shutting down due to an error:             msg="input(1, 0) Error: { expected"
DBG Stack trace:                               stack_trace="parsejson.nim(518)       raiseParseErr\n???                      start (Async)\nasyncfutures.nim(381)    read\n"
Shutting down due to an error: input(1, 0) Error: { expected
parsejson.nim(518)       raiseParseErr
???                      start (Async)
asyncfutures.nim(381)    read

[Error - 6:21:16 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 6:21:16 PM] Connection to server got closed. Server will restart.
true
[Error - 6:21:16 PM] Nim Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 6:21:16 PM] Server process exited with code 1.
DBG Shutting down due to an error:             msg="input(1, 0) Error: { expected"
DBG Stack trace:                               stack_trace="parsejson.nim(518)       raiseParseErr\n???                      start (Async)\nasyncfutures.nim(381)    read\n"
Shutting down due to an error: input(1, 0) Error: { expected
parsejson.nim(518)       raiseParseErr
???                      start (Async)
asyncfutures.nim(381)    read

[Error - 6:21:16 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 6:21:16 PM] Connection to server got closed. Server will restart.
true
[Error - 6:21:16 PM] Nim Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 6:21:16 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 6:21:16 PM] Server process exited with code 1.
DBG Router: dispatching                        method=initialize id=0
DBG Initialize received...                    
DBG Registering monitor for process            pid=2480
DBG Initialize completed. Trying to start nimsuggest instances
DBG Router: sending response                   method=initialize id=0
DBG Router: dispatching                        method=initialized id=null
DBG Client initialized.                       
DBG Requesting configuration from the client  
DBG Router: dispatching                        method=textDocument/didOpen id=null
DBG New document opened for URI:               uri=file:///e%3A/test.nim
DBG Got response for the didChangeConfiguration registration: res=null
DBG Shutting down due to an error:             msg="input(1, 0) Error: { expected"
DBG Stack trace:                               stack_trace="parsejson.nim(518)       raiseParseErr\n???                      start (Async)\nasyncfutures.nim(381)    read\n"
Shutting down due to an error: input(1, 0) Error: { expected
parsejson.nim(518)       raiseParseErr
???                      start (Async)
asyncfutures.nim(381)    read

[Info  - 6:21:16 PM] Connection to server got closed. Server will restart.
true
[Error - 6:21:16 PM] Server process exited with code 1.
DBG Router: dispatching                        method=initialize id=0
DBG Initialize received...                    
DBG Registering monitor for process            pid=2480
DBG Initialize completed. Trying to start nimsuggest instances
DBG Router: sending response                   method=initialize id=0
DBG Router: dispatching                        method=initialized id=null
DBG Client initialized.                       
DBG Requesting configuration from the client  
DBG Router: dispatching                        method=textDocument/didOpen id=null
DBG New document opened for URI:               uri=file:///e%3A/test.nim
DBG Got response for the didChangeConfiguration registration: res=null
DBG Received the following configuration       configuration="[{\"project\":[],\"projectMapping\":[],\"test-project\":\"\",\"buildOnSave\":false,\"buildCommand\":\"c\",\"runOutputDirectory\":\"\",\"lintOnSave\":false,\"enableNimsuggest\":false,\"provider\":\"lsp\",\"useNimsuggestCheck\":false,\"logNimsuggest\":false,\"licenseString\":\"\",\"nimsuggestRestartTimeout\":60,\"nimprettyIndent\":0,\"nimprettyMaxLineLen\":80,\"lsp\":{\"path\":\"C:\\\\Users\\\\user\\\\AppData\\\\Local\\\\Programs\\\\nim-lang.org\\\\nimlangserver\\\\64bit\\\\nimlangserver.exe\"},\"inlayHints\":{\"typeHints\":{\"enable\":true},\"parameterHints\":{\"enable\":true},\"exceptionHints\":{\"enable\":true,\"hintStringLeft\":\"🔔\",\"hintStringRight\":\"\"}},\"debug\":{\"type\":\"lldb\"},\"notificationVerbosity\":\"info\",\"notificationTimeout\":15,\"transportMode\":\"stdio\",\"lspPort\":0}]"
DBG Auto-guessing project file for             file="e:\\test.nim"
DBG getProjectFile                             project="e:\\test.nim" fileUri="e:\\test.nim"
DBG Document associated with the following projectFile uri=file:///e%3A/test.nim projectFile="e:\\test.nim"
DBG ShowMessage                                message="Using Nim Compiler Version 2.1.99 [Windows: amd64]"
INF Starting nimsuggest                        root="e:\\test.nim" timeout=120000 path="C:\\Users\\user\\AppData\\Local\\Programs\\nim-lang.org\\nim\\64bit\\bin\\nimsuggest.exe" workingDir="C:\\Users\\user\\AppData\\Local\\Programs\\Microsoft VS Code"
DBG Parsing nimsuggest capability              capability=con
DBG Parsing nimsuggest capability              capability=exceptionInlayHints
DBG Parsing nimsuggest capability              capability=unknownFile
DBG Nimsuggest Capabilities                    capabilities="{con, exceptionInlayHints, unknownFile}"
DBG Router: dispatching                        method=textDocument/documentSymbol id=1
DBG Router: dispatching                        method=textDocument/codeAction id=2
DBG Auto-guessing project file for             file="e:\\test.nim"
DBG Router: dispatching                        method=textDocument/inlayHint id=3
DBG inlayHint received...                     
[Error - 6:21:17 PM] Server process exited with code 3221225477.
[Error - 6:21:17 PM] The Nim Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

**Comment by jmgomez** [comment]
This is progress. It seems like it may have an issue with the config that's being sent over which should be the default one, or do you have one setup? If so, please sent it over. 

On a side note, this PR which is a major refactor to the langserver is about to get merged in a few days. It has some fixes and overall better stability. You may want to check it out as it may fix your issue already: https://github.com/nim-lang/langserver/pull/225

**Comment by dreamflow** [comment]
> It seems like it may have an issue with the config that's being sent over
 > which should be the default one, or do you have one setup?
 > If so, please sent it over.

what du you mean by "config" or "one setup" ?
where can i find "config" or "one setup" ?
i will then send it to you .

settings.json of vscode :
```json
"nim.lsp.path": "C:\\Users\\user\\AppData\\Local\\Programs\\nim-lang.org\\nimlangserver\\64bit\\nimlangserver.exe",
"nim.lintOnSave": false,
```
nimlangserver.exe is also available via the %Path% env var .

**Comment by dreamflow** [comment]
> Can you retest with the latest nimlangserver from head?

yes, i've tested now with the newest nimlangserver 64bit `1.5.1`
( from "Latest Nimlangserver Binaries" from
https://github.com/nim-lang/langserver/releases/tag/latest )

results :

it works with the (non portable)
vscode standard installation version
VSCodeUserSetup-x64-1.92.2.exe .

but it doesn't work with vscode 64bit 1.92.2 in portable mode
https://code.visualstudio.com/docs/editor/portable

there is no "output"-log-window named "Nim Lsp"
and the "output"-log-window "Nim" is empty ,
but the "output"-log-window "Extension Host'' shows :

```ruby
2024-09-10 21:19:26.430 [info] ExtensionService#_doActivateExtension NimLang.nimlang, startup: false, activationEvent: 'onLanguage:nim'
2024-09-10 21:19:26.932 [error] Activating extension NimLang.nimlang failed due to an error:
2024-09-10 21:19:26.932 [error] TypeError: Cannot read properties of undefined (reading 'uri')
	at setNimDir_553649168 (d:\portable_programs\_ from C\vscode\64bit\data\extensions\nimlang.nimlang-1.0.2\out\nimvscode.js:14978:76)
	at activate_553649241 (d:\portable_programs\_ from C\vscode\64bit\data\extensions\nimlang.nimlang-1.0.2\out\nimvscode.js:19705:5)
	at z.kb (d:\portable_programs\_ from C\vscode\64bit\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:160:13608)
	at z.jb (d:\portable_programs\_ from C\vscode\64bit\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:160:13280)
	at d:\portable_programs\_ from C\vscode\64bit\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:160:11267
	at async m.n (d:\portable_programs\_ from C\vscode\64bit\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:6409)
	at async m (d:\portable_programs\_ from C\vscode\64bit\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:6372)
	at async m.l (d:\portable_programs\_ from C\vscode\64bit\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:5829)
```

all the many other extensions in my portable vscode work fine .

**Comment by jmgomez** [comment]
> it works with the (non portable)

Great. One issue less. 

> but it doesn't work with vscode 64bit 1.92.2 in portable mode

Did you test it with the custom build of the extension that I sent over? Because the error looks quite similar to the one above

**Comment by dreamflow** [comment]
> Did you test it with the custom build of the extension that I sent over?

in `vscode 64bit 1.92.2 in portable mode` i've disabled
all extensions and then installed your custom build
`nimvscode-1.0.3.vsix` of the `nim-lang.org`-extension .
`nim -v = 2.1.99 [Windows: amd64] Compiled at 2024-09-11` .
the newest `nimlangserver 64bit 1.5.1` .
when i drag-&-drop a nim file into vscode , there is now
the empty "output"-log-window named "Nim Lsp" , but
the log-window ''Extension Host''("trace"-mode) shows :

```ruby
2024-09-11 08:32:28.998 [info] ExtensionService#_doActivateExtension NimLang.nimlang, startup: false, activationEvent: 'onLanguage:nim'
2024-09-11 08:32:28.999 [trace] ExtensionService#loadCommonJSModule file:///d:/portable_programs/_ from C/vscode/64bit/data/extensions/nimlang.nimlang-1.0.3/out/nimvscode.js
2024-09-11 08:32:28.999 [trace] ExtensionService#loadExtensionContext NimLang.nimlang
2024-09-11 08:32:29.640 [trace] ExtensionService#_callActivateOptional NimLang.nimlang
2024-09-11 08:32:29.641 [trace] ExtHostCommands#registerCommand nim.run.file
2024-09-11 08:32:29.642 [trace] ExtHostCommands#registerCommand nim.debug.file
2024-09-11 08:32:29.642 [trace] ExtHostCommands#registerCommand nim.check
2024-09-11 08:32:29.642 [trace] ExtHostCommands#registerCommand nim.restartNimsuggest
2024-09-11 08:32:29.643 [trace] ExtHostCommands#registerCommand nim.execSelectionInTerminal
2024-09-11 08:32:29.643 [trace] ExtHostCommands#registerCommand nim.clearCaches
2024-09-11 08:32:29.643 [trace] ExtHostCommands#registerCommand nim.listCandidateProjects
2024-09-11 08:32:29.643 [trace] ExtHostCommands#registerCommand nim.showNimLangServerStatus
2024-09-11 08:32:29.643 [trace] ExtHostCommands#registerCommand nim.showNotification
2024-09-11 08:32:29.644 [trace] ExtHostCommands#registerCommand nim.onDeleteNotification
2024-09-11 08:32:29.644 [trace] ExtHostCommands#registerCommand nim.onClearAllNotifications
2024-09-11 08:32:29.649 [error] Activating extension NimLang.nimlang failed due to an error:
2024-09-11 08:32:29.649 [error] TypeError: Cannot read properties of undefined (reading 'uri')
	at setNimDir_553649167 (d:\portable_programs\_ from C\vscode\64bit\data\extensions\nimlang.nimlang-1.0.3\out\nimvscode.js:14987:76)
	at activate_553649247 (d:\portable_programs\_ from C\vscode\64bit\data\extensions\nimlang.nimlang-1.0.3\out\nimvscode.js:19860:5)
	at z.kb (d:\portable_programs\_ from C\vscode\64bit\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:160:13608)
	at z.jb (d:\portable_programs\_ from C\vscode\64bit\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:160:13280)
	at d:\portable_programs\_ from C\vscode\64bit\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:160:11267
	at async m.n (d:\portable_programs\_ from C\vscode\64bit\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:6409)
	at async m (d:\portable_programs\_ from C\vscode\64bit\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:6372)
	at async m.l (d:\portable_programs\_ from C\vscode\64bit\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:5829)
2024-09-11 08:32:29.650 [trace] [vscode.merge-conflict] INVOKE provider 'x=>x.provideCodeLenses(u.URI.revive(G),J)'
2024-09-11 08:32:29.653 [trace] ExtHostCommands#executeCommand setContext
2024-09-11 08:32:29.653 [trace] ExtHostCommands#executeCommand _setContext
2024-09-11 08:32:29.653 [trace] [vscode.merge-conflict] provider DONE after 3ms
```

independent of the above , a difference of
vscode standard vs vscode in portable mode :
in vscode in portable mode , the env-var VSCODE_PORTABLE
is available and holds the absolute dir path to the "data\"-dir .
for example "extensions\"-dir and "user-data\"-dir are
reachable via
"{VSCODE_PORTABLE}\extensions\"
"{VSCODE_PORTABLE}\user-data\"

**Comment by aftamat4ik** [comment]
this problem still actual for vscode 1.100.2 in portable mode and nimlangserver v1.12.0

![As you can see](https://github.com/user-attachments/assets/91b98e1f-a84e-4e6c-94be-adbec4c5c737)

List of extensions that i'm using:
Microsoft's 'C/C++ Extension Pack'
Microsoft's CMake Tools
LLVM's clangd
Native Debug
and, ofc, vscode-nim itself
you should know also that calling 'nimlangserver.exe' from console - works fine.

![Image](https://github.com/user-attachments/assets/73efdfde-b49b-4293-aed6-168197bda28a)

Also, problem appeared after i updated my 'vscode-nim' from previous version (i guess it was 1.6.0) to 1.8.0
